server:
  port: 9010
spring:
  main:
    banner-mode: off
  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:orclcdb
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring_user
    password: spring_password
    driver-class-oracle: jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect
  kafka:
    bootstrap-servers: localhost:9092
    allow-auto-create-topics: false
    streams:
      application-id: kafka-oracle-consumer
    consumer:
      group-id: kafka-oracle-group
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org.hibernate.SQL: debug
kafka:
  topics:
    bank-accounts-topic: bank-accounts
    addresses-topic: addresses