server:
  port: 9005
spring:
  profiles:
    active: local-random, kafka-on-local
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: address-generator
            bank-accounts-input:
              consumer:
                group-id: address-generator-group
      bindings:
        bank-accounts-input:
          destination: bank-accounts
        addresses-output:
          destination: addresses
random-api:
  base-url: https://randomapi.com
  random-numeric-uri: /api/gad5rvpe?key=RUV5-EEJO-CLK9-Z6G1&max={max}
---
spring:
  profiles: kafka-on-local
  kafka:
    bootstrap-servers: localhost:9092
#---
#spring:
#  profiles: kafka-on-macbook
#  kafka:
#    bootstrap-servers: 192.168.0.103:9092