server:
  port: 9005
spring:
  profiles:
    active: local-random, kafka-on-macbook
  cloud:
    stream:
      bindings:
        bank-accounts-input:
          destination: bank-accounts
        addresses-output:
          destination: addresses
random-api:
  base-url: https://randomapi.com
  random-numeric-uri: /api/gad5rvpe?key=RUV5-EEJO-CLK9-Z6G1&max={max}
---
spring:
  profiles: kafka-on-macbook
  kafka:
    bootstrap-servers: 192.168.0.103:9092