/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shotin.blacklist.loader;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class OracleTarantoolLoaderApplication {

    public static void main(String[] args) {
        SpringApplication.run(OracleTarantoolLoaderApplication.class, args);
    }
}
