/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jmxlesson;

import javax.management.*;
import java.lang.management.ManagementFactory;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws MalformedObjectNameException, NotCompliantMBeanException, InstanceAlreadyExistsException, MBeanRegistrationException, InterruptedException {
        System.out.println(new App().getGreeting());

        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        ObjectName name = new ObjectName("jmxlesson:type="+Lesson.class.getSimpleName());
        Lesson lesson = new Lesson();
        mbs.registerMBean(lesson, name);

        System.out.println("Waiting forever...");
        Thread.sleep(Long.MAX_VALUE);
    }
}
