/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shotin.grpc;

import com.shotin.grpc.client.HelloClient;
import io.grpc.stub.StreamObserver;

import java.util.concurrent.atomic.AtomicReference;

public class App {
    public String getStarted() {
        return "STARTED gRPC-CLIENT";
    }

    public static void main(String[] args) {
        System.out.println(new App().getStarted());

        HelloClient helloClient = new HelloClient("localhost", 9009);

        BankAccountInfo bankAccountInfo1 = helloClient.findByUuid("db46e417-9d7c-4397-836e-e1c3aef2e417");
        System.out.println("bankAccountInfo1 = "+bankAccountInfo1);

        String greeting = helloClient.hello("Iurii", "Shotin");

        System.out.println("GREETING: " + greeting);

        final AtomicReference<String> greetingReference = new AtomicReference<>();
        helloClient.helloAsync("John", "Johnson", new StreamObserver<HelloResponse>() {

            @Override
            public void onNext(HelloResponse value) {
                greetingReference.set(value.getGreeting());
            }

            @Override
            public void onError(Throwable t) {
                System.err.println("ERROR: "+t);
            }

            @Override
            public void onCompleted() {
                System.out.println("GREETING: " + greetingReference.get());
            }
        });

        helloClient.helloAsync("John 2", "Johnson 2", new StreamObserver<HelloResponse>() {

            @Override
            public void onNext(HelloResponse value) {
                greetingReference.set(value.getGreeting());
            }

            @Override
            public void onError(Throwable t) {
                System.err.println("ERROR: "+t);
            }

            @Override
            public void onCompleted() {
                System.out.println("GREETING: " + greetingReference.get());
            }
        });

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
