server:
  port: 9011
spring:
  main:
    banner-mode: off
  datasource:
    #    url: jdbc:oracle:thin:@localhost:1521:orclcdb
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring_user
    password: spring_password
    driver-class-oracle: jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect