server:
  port: 9003
spring:
  profiles:
    active: kafka-local, 1-step
  data:
    cassandra:
      keyspace-name: bankkeyspace
      schema-action: create_if_not_exists
      port: 9042
  cloud:
    stream:
      bindings:
        bank-accounts-input:
          destination: bank-accounts
        addresses-input:
          destination: addresses
        bank-account-infos-output:
          destination: bank-account-infos
        bank-account-infos-input:
          destination: bank-account-infos

bank-accounts:
  kafka:
    topic: bank-accounts
---
spring:
  profiles: kafka-local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bank-accounts-group
---
spring:
  profiles: kafka-on-macbook
  kafka:
    bootstrap-servers: 192.168.0.103:9092
    consumer:
      group-id: bank-accounts-group