server:
  port: 9003
spring:
  profiles:
    active: kafka-on-macbook
bank-accounts:
  kafka:
    topic: bank-accounts
---
spring:
  profiles: kafka-on-macbook
  kafka:
    bootstrap-servers: 192.168.0.103:9092
    consumer:
      group-id: bank-accounts-group