swagger: '2.0'
info:
  version: 1.0.0
  title: Simple Artist API
  description: A simple API to understand the Swagger Specification in greater detail

schemes:
- https

host: example.io
basePath: /v1

securityDefinitions:
  UserSecurity:
    type: basic

security:
  - UserSecurity: []

paths:
  /artists:
    get:
      description: Returns a list of artists
# ----- Added lines --------------------
      parameters:
        - name: limit
          in: query
          type: integer
          descritption: Limits the number of items on a page
        - name: offset
          in: query
          type: integer
          description: Specifies the page number of the artists to be displayed
# ----- /Added lines --------------------
      
      responses:
        200:
          desription: Successfullt returned a list of artists
          schema:
            type: array
            items:
              type: object
              required:
                - username
              properties:
                artist_name:
                  type: string
                artist_genre:
                  type: string
                albums_recorded:
                  type: integer
                username:
                  type: string

        400:
          description: Invalid request
          schema:
            type: object
            properties:
              message:
                type: string
