server:
  port: 9002
bank-accounts:
  kafka:
    topic: bank-accounts
bank-account-generator:
  timeout-millis: 5000
  baseUrl: "http://localhost:9001"
  get-random-uri: "/bankAccounts/random"
  get-many-random-uri: "/bankAccounts/manyRandom/{count}"
bank-account-scheduler:
  batch-size: 10
spring:
  profiles:
    active: kafka-on-local
---
spring:
  profiles: kafka-on-local
  kafka:
    bootstrap-servers: localhost:9092
#---
#spring:
#  profiles: kafka-on-macbook
#  kafka:
#    bootstrap-servers: 192.168.0.103:9092
