---- AFTER THE kafka-oracle-consumer HAS BEEN RUN ONCE SUCCESSFULLY

ALTER TABLE SPRING_USER.BANK_ACCOUNT ADD UPDATE_ID NUMBER(18);

UPDATE SPRING_USER.BANK_ACCOUNT
SET UPDATE_ID = FLOOR(DBMS_RANDOM.value(1,2));
COMMIT;

SELECT 'INSERT INTO ADDRESS VALUES('''||BA.UUID||''', ''Москва'', ''Москва'', ''Красная Площадь'');'
FROM SPRING_USER.BANK_ACCOUNT BA
WHERE NOT EXISTS (SELECT 1 FROM ADDRESS A WHERE A.UUID = BA.UUID);

CREATE OR REPLACE VIEW SPRING_USER.BANK_ACCOUNT_INFO 
	(UUID, UPDATE_ID, LAST_NAME, FIRST_NAME, PATRONYMIC, CITY, BLACK_LISTED)
	AS SELECT 
        BA.UUID, 
        BA.UPDATE_ID,
        BA.LAST_NAME, 
        BA.FIRST_NAME, 
        BA.PATRONYMIC, 
        A.CITY, 
        FLOOR(DBMS_RANDOM.value(0,2))
	FROM BANK_ACCOUNT BA
    JOIN ADDRESS A ON A.UUID = BA.UUID;
    
SELECT * FROM SPRING_USER.BANK_ACCOUNT_INFO ORDER BY LAST_NAME, FIRST_NAME, PATRONYMIC;