---- AFTER THE kafka-oracle-consumer HAS BEEN RUN ONCE SUCCESSFULLY

CREATE OR REPLACE VIEW SPRING_USER.BANK_ACCOUNT_INFO 
	(UUID, LAST_NAME, FIRST_NAME, PATRONYMIC, CITY, BLACK_LISTED)
	AS SELECT 
        BA.UUID, 
        BA.LAST_NAME, 
        BA.FIRST_NAME, 
        BA.PATRONYMIC, 
        A.CITY, 
        FLOOR(DBMS_RANDOM.value(0,2))
	FROM BANK_ACCOUNT BA
    JOIN ADDRESS A ON A.UUID = BA.UUID;
    
SELECT * FROM SPRING_USER.BANK_ACCOUNT_INFO ORDER BY LAST_NAME;